apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: localhost:5000/ticketing-payments
          env:
            - name: EXPIRATION_WINDOW_SECONDS
              value: "5" # number of seconds
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv:27017/payments'
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_TEST_API_KEY
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_URI
              value: 'http://nats-clusterip-srv:4222'
            - name: NATS_CLIENT_ID
              valueFrom: 
                fieldRef: 
                    fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: payments-clusterip-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
